---
title: "BLI"
author: "Claire Levy"
date: "September 12, 2016"
output: html_document
---


```{r read in RAW, message = FALSE, warning = FALSE}
library(stringr)
library(dplyr)
library(ggplot2)
library(reshape2)


#I took the original .xls file, shifted over all the column headers by one and called the first column header "Time" and then saved it as a .csv

#.csv read in WAY faster than the .xls
rawDat<-read.csv("Blair_data\\RawData0_edit.csv")

anyNA(rawDat)

which(is.na(rawDat))


#just take the rows with obs in them??
r<-rawDat[1:4648,]

anyNA(r)#still true...
sum(is.na(r))#there are still 16 rows with NAs

r[which(is.na(r)),]

s<- na.omit(rawDat) #this removed 1 row (1 less obs than r)

s[which(is.na(s)),]

anyNA(s)#now False

t<-na.omit(rawDat)#this also removes 1 row

anyNA(t)

#I only want the data from the rows where Time is >= 330 


rawDatShort <- rawDat %>%
  filter(Time >= 330.0)


#check for NA's

withNA<-rawDatShort[which(is.na(rawDatShort)),]

#For all the cols with no header (Time columns), R has called them X, X.1, X.2 etc. This is ok, we can identify and remove them since there is no column that we WANT called X. The other columns (A1 etc) are shift data describing combinations of Ab/Env, which we want to keep.

# Melt the data:
#Keep the Time column, melt all the other columns so  what started as column names are now rows in a column called Sensor.Location (this matches what the corresponding column in the key is called)and the shift data is in a single column called shift.

meltRaw<- melt(rawDatShort, id.vars = "Time", variable.name = "Sensor.Location", value.name = "Shift")


#All the rows with X in the Sensor.Location column are actually repeated time data that we dont want, so I'm removing them:

#I am re-factoring here too the X's don't show up anymore when I look at the levels.

meltRawClean <- meltRaw %>%
  filter(!str_detect(Sensor.Location, "X"))%>%
  mutate(Sensor.Location = factor(Sensor.Location))
```


```{r add key, message = FALSE, warning = FALSE}
#read in the  key explaining what env and Ab were combined to get the readout in the raw data.
key<- read.csv("Blair_data/key.csv")


#We only care about some of the columns.
#Sensor.Location corresponds to the column in the melted raw data of the same name. This is an indentifier for a Env/Ab combination.
#Sample.ID is the env
#Loading Sample Id is the Ab

key <- key %>%
  select(Sensor.Location,Sample.ID,Loading.Sample.ID)

#merge the key and the melted data by the Ab/Env combination identifier ("Sensor Location")
keyAndMelted<-merge(key, meltRawClean, by = "Sensor.Location")

```


```{r extract the control data, message = FALSE, warning = FALSE}

#Put the control data in its own df.
control<- keyAndMelted %>%
  filter(str_detect(Loading.Sample.ID,"control"))

#Remove the control data from the experimental data

keyAndMeltedNoControl <- keyAndMelted %>%
  filter(!str_detect(Loading.Sample.ID,"control"))
```




```{r background subtraction, message = FALSE, warning = FALSE}


#We want to substract the background control shift values from the corresponding experimental shift values.

#Corresponding control and experimental data share the same letter in the "Sensor Location" column and the same time in the Time column. 

# Example: For any row of experimental data with "A" in Sensor Location, subtract the control shift value from the control data with "A" in the sensor location and a matching time. There is only one row of control data with "A". 


#How to do what it says above:

# Make a new column in both the control and keyAndMeltedNoControl dataframes that indicates the letter part of the "Sensor location." Call it "SensorLocLetter"

#Merge the two data frames based on the SensorLocLetter column AND the Time column. This causes each  experimental data point AND its corresponding control data point to be in the same row.

#Make a new column that is the difference between the experimental shift column and the control shift column.



#Get letters
control <- control %>%
  mutate(SensorLocLetter = str_extract(Sensor.Location, "[A-Z]"))

#repeat with experimental data:

keyAndMeltedNoControl<-keyAndMeltedNoControl %>%
    mutate(SensorLocLetter = str_extract(Sensor.Location, "[A-Z]"))


#Merge on SensorLocLetter and Time
#all.x and all.y = true will add rows with NAs for any instances where there were non-matches

mergeExpAndCntl<- merge(keyAndMeltedNoControl, control, by = c("SensorLocLetter", "Time"), all.x = TRUE, all.y = TRUE)


#Check for NA's
anyNA(mergeExpAndCntl)



#Change the column names so they make more sense

colnames(mergeExpAndCntl) <- str_replace(colnames(mergeExpAndCntl),".x",".Exp")

colnames(mergeExpAndCntl)<-
  str_replace(colnames(mergeExpAndCntl),".y",".Cntl")


#do the subtraction and add an adjusted time column(so the lowest value is zero, not 300 or whatever it is now)
mergeExpAndCntl <- mergeExpAndCntl %>%
  mutate(CorrectedShift = Shift.Exp - Shift.Cntl)%>%
  mutate(AdjTime = Time - min(Time))



withNA<- mergeExpAndCntl[which(is.na(mergeExpAndCntl)),]



#plotting
#the plots Blair made in Prism show time vs shift with different colored lines for each Env ("Sample ID"). She made different plots for each Ab ("Loading Sample ID"")


ggplot(mergeExpAndCntl, aes(x = AdjTime, y = CorrectedShift ))+
  geom_line(aes(group = Sample.ID.Exp, color = Sample.ID.Exp))+
  facet_wrap(~Loading.Sample.ID.Exp, scales = "free_y")+
  labs(x = "Time", y = "Background Corrected Shift")+
  scale_color_discrete(name = "Envelope")
```



